"""
My Agents - Custom AI agent components generated by Teach Charlie AI.

These components are auto-generated from the 3-step Q&A wizard.
Each component appears in the Langflow sidebar under "My Agents"
and can be dragged into any workflow.

DO NOT EDIT THESE FILES MANUALLY - they will be regenerated when
the agent is republished from Teach Charlie AI.
"""
