/**
 * Breadcrumb route configuration for use-react-router-breadcrumbs
 *
 * Maps routes to breadcrumb labels or custom components.
 * Dynamic segments use custom components that fetch entity names.
 */
import type { BreadcrumbsRoute } from 'use-react-router-breadcrumbs'
import { DynamicProjectBreadcrumb } from './DynamicBreadcrumbs'

export const breadcrumbRoutes: BreadcrumbsRoute[] = [
  // Hide root
  { path: '/', breadcrumb: null },

  // Dashboard (will become org name later)
  { path: '/dashboard', breadcrumb: 'Dashboard' },

  // Hide intermediate /dashboard/project path (auto-generated by library)
  { path: '/dashboard/project', breadcrumb: null },

  // Project detail
  {
    path: '/dashboard/project/:projectId',
    breadcrumb: DynamicProjectBreadcrumb,
  },

  // Settings
  { path: '/dashboard/settings', breadcrumb: 'Settings' },

  // Files
  { path: '/dashboard/files', breadcrumb: 'My Files' },

  // Legacy dashboard
  { path: '/dashboard/old', breadcrumb: 'Dashboard (Legacy)' },

  // Create agent (note: project context comes from query param, not URL)
  { path: '/create', breadcrumb: 'Create Agent' },

  // Edit agent - shows "Edit Agent" (agent name is added via useParentContext)
  {
    path: '/edit/:agentId',
    breadcrumb: 'Edit Agent',
  },

  // Hide intermediate paths
  { path: '/playground', breadcrumb: null },
  { path: '/playground/workflow', breadcrumb: null },
  { path: '/edit', breadcrumb: null },
  { path: '/canvas', breadcrumb: null },

  // Playground for agent
  {
    path: '/playground/:agentId',
    breadcrumb: 'Chat Playground',
  },

  // Playground for workflow
  {
    path: '/playground/workflow/:workflowId',
    breadcrumb: 'Chat Playground',
  },

  // Canvas viewer (uses :agentId but is actually workflow ID)
  {
    path: '/canvas/:agentId',
    breadcrumb: 'AI Canvas',
  },
]

// Routes that should exclude certain paths from breadcrumbs
export const excludePaths = ['/sign-in', '/sign-up', '/framework']
